name: RandomNick
main: Random\Main
version: 1.0
api: [3.0.0-ALPHA6, 3.0.1]
author: UltimateDevs & Zeao
commands:
  nick:
    description: "Nick yourself with a random nickname!"
    aliases: [n,nickname]
    permission: nick
    
permissions:
 nick:
  description: "Allow to give your a random nick"
  default: op
